# Generated by Django 4.2.7 on 2025-10-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обнаружения')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('row_count', models.IntegerField(default=0, verbose_name='Количество строк')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'CSV файл',
                'verbose_name_plural': 'CSV файлы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Номер строки')),
                ('data', models.JSONField(verbose_name='Данные строки')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='csv_importer.csvfile', verbose_name='CSV файл')),
            ],
            options={
                'verbose_name': 'Данные CSV',
                'verbose_name_plural': 'Данные CSV',
                'ordering': ['csv_file', 'row_number'],
            },
        ),
    ]
